# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='web_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
