# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20170119_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Berbat'), (2, 'Kötü'), (3, 'Orta'), (4, 'İyi'), (5, 'Harika')], default=3),
        ),
    ]
