# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20170119_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(upload_to='places', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='place',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Wifi?'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Mekan Adı'),
        ),
        migrations.AlterField(
            model_name='place',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='place',
            name='web_site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Web sitesi'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(null=True, verbose_name='Yorum'),
        ),
        migrations.AlterField(
            model_name='review',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Berbat'), (2, 'Kötü'), (3, 'Orta'), (4, 'İyi'), (5, 'Harika')], default=3, verbose_name='Oylama'),
        ),
    ]
